
name: Deployment

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '0 10 * * *'

env:
  GIT_NAME: "${{ secrets.GIT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
  GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Clone Repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install APT dependencies
        run: |
          sudo apt -y install dos2unix

      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install domain2idna
          pip3 install PyFunceble
          pip3 install ultimate-hosts-blacklist-whitelist

      - name: Run build
        shell: bash
        run: |
          ./dev-tools/deploy.sh
          ./dev-tools/run-pyfunceble.sh